sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
install:
  - yarn install
after_success:
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
