sudo: false
language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
script:
  - yarn lint
  - yarn test --coverage
after_success:
  - yarn release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
